### ISSUE TITLE
Invoke the debug launch config from external command line

### ISSUE THREAD

**Issue by OlofHarrysson** [bulletmark/debugpy-run#1]
Hello, I'm wondering if there is a way to launch/activate the debugger at the same time as starting debugpy-run, essentially skipping step 4 in the README.

`4. In VS Code, start debugging, e.g. set a breakpoint then start the Remote Attach debug session.`

**Comment by bulletmark** [comment]
I typically open a terminal and run `debugpy-run` then come back to main vscode window, set a breakpoint, then click to start debugging, click to step through each line, set more breakpoints, etc. So saving that one single click to start the debugger seems almost pointless to me given how many times I click when using the debugger. The debugpy-run utility is completely stand-alone from vscode (you can also run it on a remote host and connect to it from vscode remotely of course) so AFAIK there is no easy way to do what you ask.

The point of this utility is simply to make it easy to debug a command line program with different arguments each time which otherwise is painful to do via the launch config args. The debug settings in vscode are just default settings and never have to change.

**Comment by OlofHarrysson** [comment]
I understand, it seems very useful to specify the input args from the
command line that is enough. Maybe my use case would be supported through
debugpy in the future as there are others who are asking for the same thing.

Thanks for the reply:)

**Comment by bulletmark** [comment]
Note this utility has greater appeal possibly to vscode users like me that are very used to working at the command line because we can kill a command, then edit the previous line, and re-run it - all within a couple of seconds using (e.g. bash) command line history and editing functions.
