### ISSUE TITLE
Add simple support for a console script

### ISSUE THREAD

**Issue by alexdashly** [bulletmark/debugpy-run#7]
Hey, thanks for putting this together.  Really useful tool. 

I just wanted to let you know of a useful little patch I am running that you might be interested in.

I included the following to try to extract the full patch in case the program is a console script:
```python
    if args.program:
        prog = args.program
        if not Path(prog).exists():
            from shutil import which

            full_prog = which(prog)
            if not Path(full_prog).exists():
                opt.error(f'No such file: {prog}.')
            else:
                prog = full_prog
        mainargs = prog
```

This lets me run `debugpy-run my_console_script -- <script args>` for a package/library that installs a console script.

**Comment by bulletmark** [comment]
When you suggest code changes to a project you should not create an issue. You should create a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) so the reviewer can conveniently see exactly (i.e. a code diff) what you are changing. That is what pull requests are for. Or, for a simple change like here, at least paste a diff.

If you are debugging a program then you should be explicit about which program that is so this utility expects you type the file path to that program. That path can be absolute or relative of course. Otherwise the user could quite feasibly end up debugging a program they did not intend which would be very confusing. So sorry, but I disagree with this suggestion.

**Comment by alexdashly** [comment]
Thanks for the lesson I didn't ask for.  Have a good one.
